version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app
    ports:
      - 9000:5000
    environment:
      PORT: 5000
      MONGODB: 'mongodb://root:root@mongo:27017/game?authSource=admin'

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: game
  
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
